theme: jekyll-theme-slate

title: "Beyond Analytics: the Evolution of Stream Processing Systems"
description: "Tutorial for the 2020 ACM SIGMOD International Conference on Management of Data"
show_downloads: false
